/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Airlines;



import Business.Airlines;
import Business.AirlineDirectory;
import Business.Flight;
import Business.FlightDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author DAVE
 */
public class CreateSchedule extends javax.swing.JPanel {

    private Airlines airlines;
    private JPanel bottomPanel;
    public CreateSchedule(JPanel bottomPanel, Airlines airlines) {
        initComponents();
       
        this.bottomPanel= bottomPanel;
        this.airlines= airlines;
    }

    CreateSchedule(JPanel bottomPanel, AirlineDirectory AirlineDirectory) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PriceTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SeatTxtField = new javax.swing.JTextField();
        DestTxtField = new javax.swing.JTextField();
        SourceTextField = new javax.swing.JTextField();
        FlightNumberTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        timePicker1 = new com.github.lgooddatepicker.components.TimePicker();
        datePicker2 = new com.github.lgooddatepicker.components.DatePicker();
        timePicker2 = new com.github.lgooddatepicker.components.TimePicker();

        setBackground(new java.awt.Color(102, 153, 240));

        jLabel7.setText("Depatrure Date :");
        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel6.setText("Price :");
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel5.setText("AvailabeSeats: ");
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        Back.setText("<<Back");
        Back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel4.setText("Destination:");
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        Save.setText("Save");
        Save.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        jLabel2.setText("Flight Number :");
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        PriceTxtField.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PriceTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceTxtFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Create Flight Schedule");
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        SeatTxtField.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        DestTxtField.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        SourceTextField.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SourceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SourceTextFieldActionPerformed(evt);
            }
        });

        FlightNumberTxtField.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel3.setText("Source : ");
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel8.setText("Arrival Date :");
        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel9.setText("Departure Time :");
        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel10.setText("Arrival Date :");
        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Back)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(183, 183, 183)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(DestTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(147, 147, 147)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FlightNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(PriceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(SeatTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(136, 136, 136)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(Save)
                                    .addGap(76, 76, 76))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(62, 62, 62))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(timePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(datePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(timePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(62, 62, 62))))))
                .addContainerGap(509, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Back)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlightNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DestTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SeatTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(PriceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(timePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(datePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(timePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(Save)
                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        bottomPanel.remove(this);
        Component[] componentArray = bottomPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAirlinesCatalog manageAirlineCatalogJPanel = (ManageAirlinesCatalog) component;
        manageAirlineCatalogJPanel.populate1();
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.previous(bottomPanel);
    }//GEN-LAST:event_BackActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        //   Flights flights = airlines.getFlightsDict().addFlight();
        if(FlightNumberTxtField.getText().isEmpty() && SourceTextField.getText().isEmpty() && DestTxtField.getText().isEmpty() &&
            datePicker1.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter all the details correctly");
        }
        else{
                String number = FlightNumberTxtField.getText().trim();
                if(number==null || number.equals("")){
                JOptionPane.showMessageDialog(null, "Flight Number cannot be Empty. Enter Flight Number");
                return;
            }
            
            String src = SourceTextField.getText().trim();
                if(src==null || src.equals("")){
                JOptionPane.showMessageDialog(null, "Source cannot be Empty. Enter Source");
                return;
            }
            else if(! src.matches("^[a-zA-Z]+$")){
                JOptionPane.showMessageDialog(null,"Enter Valid Source. Only Alphabets");
                return;}
            
            String dest = DestTxtField.getText().trim();
                if(dest==null || dest.equals("")){
                JOptionPane.showMessageDialog(null, "Destination cannot be Empty. Enter Destination");
                return;
            }
            else if(! dest.matches("^[a-zA-Z]+$")){
                JOptionPane.showMessageDialog(null,"Enter Valid Destination. Only Alphabets");
                return;}
            
            int sea = Integer.parseInt(SeatTxtField.getText().trim());
                String pr =(PriceTxtField.getText().trim());
                 try{
               Integer.parseInt(pr);
               
           }catch(NumberFormatException e){
               JOptionPane.showMessageDialog(null, "Enter Valid Price");
               return;
           }
           if(pr==null || pr.equals("")){
              JOptionPane.showMessageDialog(null, "Text Field cannot be Empty. Enter Price");
                return; 
           }
                
                String date = datePicker1.getText().trim();
                if(date==null || date.equals("")){
                JOptionPane.showMessageDialog(null, "Departure Date cannot be Empty");
                return;
            }
                
                String time = timePicker1.getText().trim();
                if(time==null || time.equals("")){
                JOptionPane.showMessageDialog(null, "Departure Time cannot be Empty");
                return;
            }
                String Adate = datePicker2.getText().trim();
                if(Adate==null || Adate.equals("")){
                JOptionPane.showMessageDialog(null, " Date cannot be Empty");
                return;}
                String Atime = timePicker2.getText().trim();
                if(Atime==null || Atime.equals("")){
                JOptionPane.showMessageDialog(null, "Arrival Time cannot be Empty");
                return;
            }
                
                Flight flights = airlines.getFlight().addData();
                flights.setFlightNum(number);
                flights.setSource(src);
                flights.setDest(dest);
                flights.setSeat(sea);
                flights.setPrice(Integer.parseInt(pr));
                flights.setdate(date);
                flights.setTime(time);
                flights.setAdate(Adate);
                flights.setAtime(Atime);
               

                JOptionPane.showMessageDialog(null, "Schedule Created Successfully");

                FlightNumberTxtField.setText("");
                SourceTextField.setText("");
                DestTxtField.setText("");
                SeatTxtField.setText("");
                PriceTxtField.setText("");
                datePicker1.setText("");
                timePicker1.setText("");
                datePicker2.setText("");
                timePicker2.setText("");
                   
            
           
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void PriceTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceTxtFieldActionPerformed

    private void SourceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SourceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SourceTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField DestTxtField;
    private javax.swing.JTextField FlightNumberTxtField;
    private javax.swing.JTextField PriceTxtField;
    private javax.swing.JButton Save;
    private javax.swing.JTextField SeatTxtField;
    private javax.swing.JTextField SourceTextField;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private com.github.lgooddatepicker.components.DatePicker datePicker2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.github.lgooddatepicker.components.TimePicker timePicker1;
    private com.github.lgooddatepicker.components.TimePicker timePicker2;
    // End of variables declaration//GEN-END:variables
}
